- name: Create jenkins directory
  file:
    path: /home/ubuntu/jenkins_dir
    state: directory
    mode: '0777'

- name: Run Jenkins Docker
  shell: "sudo docker run -d -p 8080:8080 -p 50000:50000 --restart=on-failure -v /home/ubuntu/jenkins_dir:/var/jenkins_home jenkins/jenkins:lts-jdk11"

- name: Get AdminPass
  shell: "sudo cat /home/ubuntu/jenkins_dir/secrets/initialAdminPassword"
  register: jenkins_password
  retries: 6
  delay: 5
  until: jenkins_password.rc == 0

- name: Print AdminPass
  debug: 
    var: jenkins_password.stdout

- name: Print output to file
  copy: 
    content: "{{jenkins_password.stdout}}"
    dest: ../jenkins-adminpass.txt
  delegate_to: localhost
  become: false
  become_user: taras