- name: Run Jenkins Docker
  shell: "docker run -d -p 8080:8080 -p 50000:50000 --restart=on-failure -v /home/ubuntu:/var jenkins/jenkins:lts-jdk11"

- name: Get AdminPass
  shell: "sudo cat /home/ubuntu/jenkins_home/secrets/initialAdminPassword"
  register: jenkins_password
  retries: 6
  delay: 5
  until: jenkins_password.rc == 0

- name: Print AdminPass
  debug: 
    var: jenkins_password.stdout

- name: Print output to file
  copy: 
    content: "{{jenkins_password.stdout}}"
    dest: ../jenkins-adnminpass.txt
  delegate_to: localhost