- name: Create root directory
  file:
    path: /site
    state: directory
    mode: '0755'

- name: Copy web-site
  copy:
    src: "{{checkout_dir}}/site"
    dest: "/"
    remote_src: yes 
    directory_mode: yes
