inventory_path: "/home/taras/.ssh"

#ansible_ssh_private_key_file: "{{inventory_path}}/aws_key.pem"
ansible_become: true

checkout_dir: /tmp/checkout

mysql_root_password: "123321"

docker_apt_gpg_key_url: "https://download.docker.com/ubuntu/debian/gpg"