- name: Create a new database
  mysql_db:
    name: display
    state: present
    login_password: "{{ mysql_root_password }}"
    
- name: Copy database dump file to remote host
  copy:
    src: display.sql
    dest: /tmp

- name: Restore the dump file to database 'display'
  mysql_db:
    name: display
    state: import
    target: /tmp/display.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"