- name: Create a new database with name 'jackdata'
  community.general.mssql_db:
    name: display
    state: present

- name: Copy database dump file to remote host
  ansible.builtin.copy:
    src: display.sql
    dest: /tmp

- name: Restore the dump file to database 'display'
  community.general.mssql_db:
    name: display
    state: import
    target: /tmp/display.sql