- name: Install mysql-server
  apt:
    name: 
    - mysql-server
    - python3-mysqldb

- name: Start mysql-server
  service:
    name: mysql.service
    state:  started

- name: Set root user password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'php'
  mysql_user:
    name: php
    host: "{{ hostvars[groups['webapp'][0]].ansible_host }}"
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL'
    state: present
    login_password: "{{ mysql_root_password }}"

- name: Comment bind
  shell: sed -i 's/^bind-address/#bind-address/' /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Start mysql-server
  service:
    name: mysql
    state:  restarted