- name: Install haproxy
  apt:
    name:
      - haproxy
    state: present

- name: Generate config
  template:
    src: files/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Restart Haproxy
  service:
    name: haproxy
    state: restarted