- name: Enable ip forward
  shell: sudo sysctl -w net.ipv4.ip_forward=1

- name: Flush nat table
  shell: sudo iptables -t nat -F

- name: Route ports 22
  shell: sudo iptables -t nat -A PREROUTING -p tcp --dport "{{ item.value }}" -j DNAT --to-destination "{{ item.key }}":22
  loop: "{{ip_port_for_nat|dict2items}}"

- name: Route port 3306
  shell: sudo iptables -t nat -A PREROUTING -p tcp --dport "{{ item }}" -j DNAT --to-destination "{{ jenkins_sql_local_ip }}":"{{ item }}"
  loop:
  - 3306
  #- 8080

- name: Enable masquerade
  shell: sudo iptables -t nat -A POSTROUTING ! -s 127.0.0.1 -j MASQUERADE

- name: Save iptables
  shell: sudo /sbin/iptables-save > /etc/network/iptables.rules