- name: Install required apt
  apt:
    name: 
    - ca-certificates
    - curl
    - gnupg

- name: Add an Apt signing key
  apt_key:
    url: "{{ docker_apt_gpg_key_url }}"
    state: present

- name: Get Architecture
  shell: dpkg --print-architecture
  register: architecture

- name: Add specified repository into sources list
  apt_repository:
    repo: deb [arch={{ architecture.stdout }}] "{{ docker_apt_url }}" {{ hostvars[inventory_hostname].ansible_distribution_release }} stable
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
  with_items:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io