- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_gpg_key_url }}"
    state: present

- name: Get Architecture
  shell: dpkg --print-architecture
  register: architecture

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/debian {{ hostvars[inventory_hostname].ansible_distribution_release }} stable
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
  with_items:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io